repos:
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    args:
    - --baseline
    - .secrets.baseline
- repo: https://github.com/amperser/proselint
  rev: v0.16.0
  hooks:
  - id: proselint
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.2
  hooks:
  - id: codespell
    args:
    - --ignore-words-list
    - foobar
    - --skip=*.pyc,*.svg,*.json
- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.16.4
  hooks:
  - id: commitizen
    stages:
    - commit-msg
- repo: https://github.com/crate-ci/typos
  rev: v1
  hooks:
  - id: typos
- repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
  hooks:
  - id: cargo-check
    args:
    - --workspace
  - id: clippy
    args:
    - --
    - -D
    - warnings
  - id: fmt
    args:
    - --
    - --check
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.30.0
  hooks:
  - id: gitleaks
- repo: https://github.com/google/yamlfmt
  rev: v0.21.0
  hooks:
  - id: yamlfmt
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
- repo: https://github.com/nim65s/pre-commit-sort
  rev: v1.0.0
  hooks:
  - id: pre-commit-sort
- repo: https://github.com/owenlamont/ryl-pre-commit
  rev: v0.21.0
  hooks:
  - id: ryl
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
  - id: debug-statements
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: file-contents-sorter
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: name-tests-test
  - id: no-commit-to-branch
  - id: pretty-format-json
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/rvben/rumdl-pre-commit
  rev: v0.2.26
  hooks:
  - id: rumdl-fmt
- repo: https://github.com/semgrep/semgrep
  rev: v1.165.0
  hooks:
  - id: semgrep
    args:
    - --config
    - auto
    - --error
- repo: https://github.com/thlorenz/doctoc
  rev: v2.5.0
  hooks:
  - id: doctoc
- repo: https://github.com/thoughtworks/talisman
  rev: v1.37.0
  hooks:
  - id: talisman-commit
- repo: https://github.com/trufflesecurity/truffleHog
  rev: v3.95.7
  hooks:
  - id: trufflehog
    args:
    - --only-verified
    stages:
    - pre-commit
    - pre-push
- repo: https://github.com/zizmorcore/zizmor-pre-commit
  rev: v1.26.1
  hooks:
  - id: zizmor
- repo: meta
  hooks:
  - id: check-useless-excludes
